### PR TITLE
Initial update docs

### PR DESCRIPTION
**Pull request by withcenter-dev2**
Added few chat.md docs.

No changes on code.

### CODE REVIEW

**Review by thruthesky — COMMENTED** [review]
This has conflict.

**Review by thruthesky — CHANGES_REQUESTED** [review]
Fix error.

**Comment by withcenter-dev2** [comment]
Conflicts resolved

**Review by withcenter-dev2 — COMMENTED** [review]
Merge was resolved for flutter plugins, flutter plugins dependencies

**Review by thruthesky — APPROVED** [review]

**Review by thruthesky — APPROVED** [review]
Merge from doc

**Pull request merged**
